#!/bin/sh
# ==========================
# Git Hook: commit-msg
# Validación opcional con CheckCommit
# Se ejecuta SOLO si el mensaje contiene una palabra clave
# ==========================

# 🔧 Configura tus rutas aquí
CHECKCOMMIT_EXE="D:/ChecklistCommit/program/Checklist.exe"
CHECKLIST_DIR="D:/ChecklistCommit"
REPORT_PATH="D:\ChecklistCommit\dotnet\checkcommit_report.md"

# Palabra clave que activa la validación
KEYWORD="#checkList"

# Obtener el mensaje del commit
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Verificar si contiene la palabra clave
echo "$COMMIT_MSG" | grep -qi "$KEYWORD"
if [ $? -eq 0 ]; then
    echo "🔍 Validando checklist con Gemini..."
	# Cambiar dotnet o angular
    "$CHECKCOMMIT_EXE" dotnet D:/ChecklistCommit
    STATUS=$?

    if [ $STATUS -ne 0 ]; then
        echo "❌ Commit bloqueado: revisa el reporte en:"
        echo "📄 file:///$REPORT_PATH"
        # Abrir carpeta del reporte (Windows)
        explorer $REPORT_PATH
        exit 1
    fi

    echo "✅ Validación completada."
else
    echo "⚡ Checklist omitido (no se encontró la palabra clave '$KEYWORD')."
fi

exit 0
